import type { ProdottoFood } from '@/lib/tipi'

/**
 * Banco alimentari.
 *
 * Come per le locandine, le fotografie non ci sono: `immagine` è vuota e la
 * scheda disegna un'illustrazione procedurale dai due colori di `palette`.
 * Sostituirle con le fotografie vere del banco è la prima cosa da fare in
 * produzione — sul food la fotografia vende più della descrizione.
 *
 * Gli allergeni sono dichiarati perché in Italia è un obbligo di legge
 * (Reg. UE 1169/2011) e non un dettaglio grafico: il campo esiste nello schema,
 * il pannello lo chiede e la scheda lo mostra sempre, anche quando è vuoto.
 */

function prodotto(dati: Omit<ProdottoFood, 'immagine' | 'cinemaIds'> & { cinemaIds?: string[] }): ProdottoFood {
  return { immagine: '', cinemaIds: [], ...dati }
}

export const FOOD_INIZIALE: ProdottoFood[] = [
  /* ── Popcorn ─────────────────────────────────────────────────────────── */
  prodotto({
    id: 'foo-pop-s',
    nome: 'Popcorn piccolo',
    descrizione: 'Mais a fiocco grande, burro leggero. Il formato da una persona.',
    categoria: 'Popcorn',
    prezzo: 3.9,
    palette: ['#4a3410', '#ffd166'],
    allergeni: ['Latte'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 1,
  }),
  prodotto({
    id: 'foo-pop-m',
    nome: 'Popcorn medio',
    descrizione: 'Il formato da condividere in due, se si riesce.',
    categoria: 'Popcorn',
    prezzo: 5.5,
    palette: ['#4a3410', '#ffd166'],
    allergeni: ['Latte'],
    contenuto: [],
    disponibile: true,
    inEvidenza: true,
    ordine: 2,
  }),
  prodotto({
    id: 'foo-pop-l',
    nome: 'Popcorn grande',
    descrizione: 'Secchiello da famiglia, con ricarica gratuita al banco.',
    categoria: 'Popcorn',
    prezzo: 7.5,
    palette: ['#4a3410', '#ffe08a'],
    allergeni: ['Latte'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 3,
  }),
  prodotto({
    id: 'foo-pop-caramel',
    nome: 'Popcorn caramellati',
    descrizione: 'Caramello salato, preparati al momento.',
    categoria: 'Popcorn',
    prezzo: 6.5,
    palette: ['#5a2f0d', '#f4a261'],
    allergeni: ['Latte', 'Soia'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 4,
  }),

  /* ── Nachos ──────────────────────────────────────────────────────────── */
  prodotto({
    id: 'foo-nachos',
    nome: 'Nachos con formaggio',
    descrizione: 'Tortilla di mais e salsa cheddar calda.',
    categoria: 'Nachos',
    prezzo: 6.2,
    palette: ['#5a3a08', '#ffc93c'],
    allergeni: ['Latte'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 5,
  }),
  prodotto({
    id: 'foo-nachos-jala',
    nome: 'Nachos jalapeños',
    descrizione: 'Cheddar, jalapeños e salsa piccante a parte.',
    categoria: 'Nachos',
    prezzo: 6.9,
    palette: ['#2f4f14', '#a3e635'],
    allergeni: ['Latte'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 6,
  }),

  /* ── Bibite ──────────────────────────────────────────────────────────── */
  prodotto({
    id: 'foo-bib-m',
    nome: 'Bibita media',
    descrizione: 'Cola, aranciata, limonata o tè freddo. 40 cl.',
    categoria: 'Bibite',
    prezzo: 3.5,
    palette: ['#2a1a3a', '#ff6b8e'],
    allergeni: [],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 7,
  }),
  prodotto({
    id: 'foo-bib-l',
    nome: 'Bibita grande',
    descrizione: '70 cl, con ricarica gratuita al banco.',
    categoria: 'Bibite',
    prezzo: 4.5,
    palette: ['#2a1a3a', '#ff8fa8'],
    allergeni: [],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 8,
  }),
  prodotto({
    id: 'foo-acqua',
    nome: 'Acqua naturale 50 cl',
    descrizione: 'Naturale o frizzante.',
    categoria: 'Bibite',
    prezzo: 1.5,
    palette: ['#123644', '#7fd4c1'],
    allergeni: [],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 9,
  }),
  prodotto({
    id: 'foo-birra',
    nome: 'Birra artigianale 33 cl',
    descrizione: 'Bionda sarda, servita fredda. Vendita vietata ai minori di 18 anni.',
    categoria: 'Bibite',
    prezzo: 5,
    palette: ['#4a3410', '#f9c74f'],
    allergeni: ['Glutine'],
    contenuto: [],
    // Non in tutte le sale: dove non c'è la licenza, il prodotto non compare
    // proprio nel carrello invece di essere proposto e poi rifiutato.
    cinemaIds: ['cin-cagliari', 'cin-sassari', 'cin-olbia'],
    disponibile: true,
    inEvidenza: false,
    ordine: 10,
  }),

  /* ── Dolci ───────────────────────────────────────────────────────────── */
  prodotto({
    id: 'foo-mms',
    nome: 'Confetti al cioccolato',
    descrizione: 'Busta da 150 g.',
    categoria: 'Dolci',
    prezzo: 3.2,
    palette: ['#3a1220', '#ff85a1'],
    allergeni: ['Latte', 'Frutta a guscio', 'Soia'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 11,
  }),
  prodotto({
    id: 'foo-gelato',
    nome: 'Gelato su stecco',
    descrizione: 'Fiordilatte ricoperto, mandorla o cioccolato fondente.',
    categoria: 'Dolci',
    prezzo: 3.8,
    palette: ['#2b2338', '#e0c3fc'],
    allergeni: ['Latte', 'Frutta a guscio'],
    contenuto: [],
    disponibile: true,
    inEvidenza: false,
    ordine: 12,
  }),
  prodotto({
    id: 'foo-seadas',
    nome: 'Seadas tiepide',
    descrizione: 'Due seadas con miele di corbezzolo. La specialità della casa.',
    categoria: 'Dolci',
    prezzo: 5.5,
    palette: ['#4a3a10', '#ffd166'],
    allergeni: ['Glutine', 'Latte', 'Uova'],
    contenuto: [],
    cinemaIds: ['cin-nuoro', 'cin-tortoli'],
    disponibile: true,
    inEvidenza: true,
    ordine: 13,
  }),

  /* ── Combo e menu ────────────────────────────────────────────────────── */
  prodotto({
    id: 'foo-combo-due',
    nome: 'Combo per due',
    descrizione: 'Il formato classico da dividere: risparmi 2,40 € rispetto ai singoli.',
    categoria: 'Combo',
    prezzo: 12,
    palette: ['#2a1040', '#ff4d7d'],
    allergeni: ['Latte'],
    contenuto: ['1 popcorn grande', '2 bibite medie'],
    disponibile: true,
    inEvidenza: true,
    ordine: 14,
  }),
  prodotto({
    id: 'foo-combo-solo',
    nome: 'Combo singolo',
    descrizione: 'Popcorn medio e bibita media.',
    categoria: 'Combo',
    prezzo: 8,
    palette: ['#1b1140', '#a06bff'],
    allergeni: ['Latte'],
    contenuto: ['1 popcorn medio', '1 bibita media'],
    disponibile: true,
    inEvidenza: false,
    ordine: 15,
  }),
  prodotto({
    id: 'foo-menu-famiglia',
    nome: 'Menu famiglia',
    descrizione: 'Per quattro persone. Risparmi 6,10 € rispetto ai prodotti singoli.',
    categoria: 'Menu',
    prezzo: 22,
    palette: ['#13263f', '#79c7ff'],
    allergeni: ['Latte'],
    contenuto: ['2 popcorn grandi', '4 bibite medie', '2 confetti al cioccolato'],
    disponibile: true,
    inEvidenza: true,
    ordine: 16,
  }),
  prodotto({
    id: 'foo-menu-nachos',
    nome: 'Menu nachos',
    descrizione: 'Per chi al popcorn preferisce il salato vero.',
    categoria: 'Menu',
    prezzo: 13.5,
    palette: ['#2f4f14', '#a3e635'],
    allergeni: ['Latte'],
    contenuto: ['2 nachos con formaggio', '2 bibite medie'],
    disponibile: true,
    inEvidenza: false,
    ordine: 17,
  }),
]
