import type { Veicolo } from '@/lib/tipi'

/**
 * Catalogo di partenza.
 *
 * Questi veicoli popolano l'archivio al primo avvio: da quel momento in poi la
 * fonte di verità è l'archivio, e le modifiche si fanno dal pannello. Il file
 * resta utile come esempio di scheda compilata bene e per ripartire da zero
 * cancellando l'archivio.
 *
 * Le fotografie sono generate da `npm run immagini` a partire dallo slug: ogni
 * veicolo ne ha quattro, la prima è la copertina. Sostituendo i file dentro
 * `public/immagini/veicoli/` con le fotografie vere, e mantenendo i nomi, non
 * serve toccare il codice.
 */

/** Percorsi delle fotografie di un veicolo, ricavati dallo slug. */
function immagini(slug: string, quante = 4): string[] {
  return Array.from({ length: quante }, (_, indice) => `/immagini/veicoli/${slug}-${indice + 1}.jpg`)
}

export const VEICOLI_INIZIALI: Veicolo[] = [
  /* ── Auto ──────────────────────────────────────────────────────────────── */
  {
    id: 'vei-audi-a4-avant',
    slug: 'audi-a4-avant-40-tdi-quattro',
    tipo: 'auto',
    marca: 'Audi',
    modello: 'A4 Avant',
    allestimento: '40 TDI quattro S line',
    anno: 2022,
    chilometri: 48_200,
    prezzo: 38_900,
    prezzoPrecedente: 41_500,
    condizione: 'usato',
    alimentazione: 'diesel',
    cambio: 'automatico',
    tipologia: 'station-wagon',
    potenzaCv: 204,
    potenzaKw: 150,
    cilindrata: 1968,
    posti: 5,
    porte: 5,
    colore: 'Grigio Daytona metallizzato',
    consumoMisto: 5.4,
    emissioniCo2: 142,
    classeEmissioni: 'Euro 6D',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'Familiare di segmento medio con trazione integrale permanente quattro e cambio S tronic a sette ' +
      'rapporti. Unico proprietario, tagliandi certificati Audi Service e gomme quattro stagioni ' +
      'sostituite a gennaio. Il vano di carico da 495 litri e il divano frazionabile 40:20:40 la rendono ' +
      'la scelta naturale per chi macina chilometri senza rinunciare allo spazio.',
    dotazioni: [
      'Trazione integrale quattro',
      'Fari Matrix LED',
      'Virtual Cockpit 12,3"',
      'Navigatore MMI Plus',
      'Sedili sportivi riscaldati',
      'Portellone elettrico',
      'Cruise control adattivo',
      'Sensori di parcheggio anteriori e posteriori',
      'Telecamera posteriore',
      'Cerchi in lega da 18"',
      'Climatizzatore trizona',
      'Apple CarPlay e Android Auto',
    ],
    immagini: immagini('audi-a4-avant-40-tdi-quattro'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-12T09:00:00.000Z',
  },
  {
    id: 'vei-bmw-320e',
    slug: 'bmw-serie-3-320e-msport',
    tipo: 'auto',
    marca: 'BMW',
    modello: 'Serie 3',
    allestimento: '320e Msport',
    anno: 2023,
    chilometri: 29_500,
    prezzo: 42_500,
    prezzoPrecedente: null,
    condizione: 'aziendale',
    alimentazione: 'ibrida-plug-in',
    cambio: 'automatico',
    tipologia: 'berlina',
    potenzaCv: 204,
    potenzaKw: 150,
    cilindrata: 1998,
    posti: 5,
    porte: 4,
    colore: 'Nero Saphir metallizzato',
    consumoMisto: 1.6,
    emissioniCo2: 37,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: 61,
    garanziaMesi: 24,
    descrizione:
      'Berlina ibrida ricaricabile proveniente da flotta aziendale, con storia manutentiva completa e ' +
      'batteria certificata al 98% della capacità originale. In città percorre l’intera giornata in ' +
      'elettrico e accede senza limitazioni alle zone a traffico controllato.',
    dotazioni: [
      'Pacchetto Msport',
      'Cavo di ricarica Mode 3',
      'Head-up display',
      'Sedili sportivi in pelle Vernasca',
      'Assistente di guida Professional',
      'Impianto hi-fi Harman Kardon',
      'Fari Adaptive LED',
      'Cerchi in lega da 19"',
      'Portellone automatico',
      'Climatizzatore automatico bizona',
    ],
    immagini: immagini('bmw-serie-3-320e-msport'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-20T09:00:00.000Z',
  },
  {
    id: 'vei-mercedes-glc',
    slug: 'mercedes-benz-glc-300-de-4matic',
    tipo: 'auto',
    marca: 'Mercedes-Benz',
    modello: 'GLC',
    allestimento: '300 de 4MATIC AMG Line',
    anno: 2025,
    chilometri: 4_800,
    prezzo: 62_900,
    prezzoPrecedente: 68_400,
    condizione: 'km-0',
    alimentazione: 'ibrida-plug-in',
    cambio: 'automatico',
    tipologia: 'suv',
    potenzaCv: 335,
    potenzaKw: 246,
    cilindrata: 1993,
    posti: 5,
    porte: 5,
    colore: 'Grigio Selenite metallizzato',
    consumoMisto: 1.1,
    emissioniCo2: 29,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: 118,
    garanziaMesi: 24,
    descrizione:
      'SUV ibrido diesel plug-in con trazione integrale 4MATIC: 118 chilometri di autonomia elettrica ' +
      'dichiarata e consumi da utilitaria nei viaggi lunghi. Vettura a chilometri zero, mai immatricolata ' +
      'a privati, con garanzia ufficiale della casa ancora interamente da godere.',
    dotazioni: [
      'AMG Line esterni e interni',
      'Trazione integrale 4MATIC',
      'MBUX con schermo verticale 11,9"',
      'Tetto panoramico apribile',
      'Sospensioni adattive',
      'Fari Digital Light',
      'Sedili anteriori riscaldati e ventilati',
      'Portellone hands-free',
      'Telecamere 360°',
      'Cerchi AMG da 20"',
      'Impianto Burmester',
      'Ricarica rapida in corrente continua',
    ],
    immagini: immagini('mercedes-benz-glc-300-de-4matic'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-02-02T09:00:00.000Z',
  },
  {
    id: 'vei-porsche-718',
    slug: 'porsche-718-cayman-gts-4-0',
    tipo: 'auto',
    marca: 'Porsche',
    modello: '718 Cayman',
    allestimento: 'GTS 4.0',
    anno: 2021,
    chilometri: 27_400,
    prezzo: 94_500,
    prezzoPrecedente: null,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'manuale',
    tipologia: 'coupe',
    potenzaCv: 400,
    potenzaKw: 294,
    cilindrata: 3995,
    posti: 2,
    porte: 2,
    colore: 'Rosso Carminio',
    consumoMisto: 10.9,
    emissioniCo2: 248,
    classeEmissioni: 'Euro 6D',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Sei cilindri boxer aspirato da quattro litri, cambio manuale a sei rapporti e differenziale ' +
      'autobloccante: una delle ultime sportive costruite così. Sempre rimessata al coperto, tagliandi ' +
      'Porsche completi, gomme nuove e nessun intervento di carrozzeria.',
    dotazioni: [
      'Pacchetto Sport Chrono',
      'Scarico sportivo',
      'Sospensioni PASM ribassate',
      'Differenziale autobloccante PTV',
      'Sedili sportivi Plus in Alcantara',
      'Impianto frenante maggiorato',
      'Cerchi da 20" satinati',
      'Porsche Communication Management',
      'Assetto ribassato di 20 mm',
    ],
    immagini: immagini('porsche-718-cayman-gts-4-0'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'vei-volkswagen-golf',
    slug: 'volkswagen-golf-1-5-etsi-life',
    tipo: 'auto',
    marca: 'Volkswagen',
    modello: 'Golf',
    allestimento: '1.5 eTSI 130 CV Life DSG',
    anno: 2026,
    chilometri: 0,
    prezzo: 31_400,
    prezzoPrecedente: 34_200,
    condizione: 'nuovo',
    alimentazione: 'ibrida',
    cambio: 'automatico',
    tipologia: 'berlina',
    potenzaCv: 130,
    potenzaKw: 96,
    cilindrata: 1498,
    posti: 5,
    porte: 5,
    colore: 'Bianco Puro',
    consumoMisto: 5.2,
    emissioniCo2: 118,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'Vettura nuova pronta consegna con micro-ibrido a 48 volt e cambio doppia frizione. La formula più ' +
      'equilibrata della gamma: consumi contenuti, manutenzione economica e un valore residuo fra i più ' +
      'solidi del segmento.',
    dotazioni: [
      'Digital Cockpit Pro',
      'Navigatore Discover Media',
      'Fari LED Plus',
      'Cruise control adattivo',
      'Climatizzatore bizona',
      'Sensori di parcheggio posteriori',
      'App-Connect wireless',
      'Cerchi in lega da 16"',
      'Frenata automatica d’emergenza',
    ],
    immagini: immagini('volkswagen-golf-1-5-etsi-life'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 59,
      settimanale: 340,
      mensile: 1090,
      cauzione: 500,
      kmInclusiGiorno: 200,
      etaMinima: 21,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-10T09:00:00.000Z',
  },
  {
    id: 'vei-fiat-500e',
    slug: 'fiat-500e-la-prima',
    tipo: 'auto',
    marca: 'Fiat',
    modello: '500e',
    allestimento: 'La Prima 42 kWh',
    anno: 2023,
    chilometri: 22_100,
    prezzo: 19_900,
    prezzoPrecedente: 22_400,
    condizione: 'usato',
    alimentazione: 'elettrica',
    cambio: 'automatico',
    tipologia: 'city-car',
    potenzaCv: 118,
    potenzaKw: 87,
    cilindrata: 0,
    posti: 4,
    porte: 3,
    colore: 'Verde Rugiada',
    consumoMisto: 14.9,
    emissioniCo2: 0,
    classeEmissioni: 'Zero emissioni',
    autonomiaKm: 320,
    garanziaMesi: 24,
    descrizione:
      'Elettrica compatta nell’allestimento più ricco, con batteria da 42 kWh e ricarica rapida a 85 kW. ' +
      'Certificato di stato batteria allegato: 94% di capacità residua. Perfetta come seconda vettura di ' +
      'famiglia o per chi si sposta ogni giorno fra Tortolì e i paesi vicini.',
    dotazioni: [
      'Ricarica rapida 85 kW',
      'Tetto in vetro',
      'Sedili in eco-pelle',
      'Navigatore con schermo da 10,25"',
      'Sensori di parcheggio con telecamera',
      'Cerchi in lega diamantati da 17"',
      'Climatizzatore automatico',
      'Cavo di ricarica domestico',
      'Guida autonoma di livello 2',
    ],
    immagini: immagini('fiat-500e-la-prima'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 45,
      settimanale: 265,
      mensile: 830,
      cauzione: 400,
      kmInclusiGiorno: 150,
      etaMinima: 21,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-01-28T09:00:00.000Z',
  },
  {
    id: 'vei-jeep-avenger',
    slug: 'jeep-avenger-e-hybrid-altitude',
    tipo: 'auto',
    marca: 'Jeep',
    modello: 'Avenger',
    allestimento: 'e-Hybrid Altitude',
    anno: 2025,
    chilometri: 3_400,
    prezzo: 27_900,
    prezzoPrecedente: null,
    condizione: 'km-0',
    alimentazione: 'ibrida',
    cambio: 'automatico',
    tipologia: 'suv',
    potenzaCv: 136,
    potenzaKw: 100,
    cilindrata: 1199,
    posti: 5,
    porte: 5,
    colore: 'Blu Sun',
    consumoMisto: 5.5,
    emissioniCo2: 124,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'SUV compatto ibrido a chilometri zero, con protezioni sottoscocca e altezza da terra generosa: ' +
      'sta comodo in un parcheggio del centro e non si spaventa sulle strade bianche dell’entroterra.',
    dotazioni: [
      'Selettore Selec-Terrain',
      'Schermo Uconnect da 10,25"',
      'Retrocamera',
      'Sensori anteriori e posteriori',
      'Cerchi in lega da 17"',
      'Climatizzatore automatico',
      'Barre al tetto',
      'Keyless entry',
    ],
    immagini: immagini('jeep-avenger-e-hybrid-altitude'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 69,
      settimanale: 399,
      mensile: 1250,
      cauzione: 600,
      kmInclusiGiorno: 200,
      etaMinima: 23,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-14T09:00:00.000Z',
  },
  {
    id: 'vei-toyota-yaris-cross',
    slug: 'toyota-yaris-cross-hybrid-lounge',
    tipo: 'auto',
    marca: 'Toyota',
    modello: 'Yaris Cross',
    allestimento: '1.5 Hybrid Lounge',
    anno: 2023,
    chilometri: 31_800,
    prezzo: 26_400,
    prezzoPrecedente: null,
    condizione: 'usato',
    alimentazione: 'ibrida',
    cambio: 'automatico',
    tipologia: 'suv',
    potenzaCv: 116,
    potenzaKw: 85,
    cilindrata: 1490,
    posti: 5,
    porte: 5,
    colore: 'Bronzo metallizzato',
    consumoMisto: 4.4,
    emissioniCo2: 100,
    classeEmissioni: 'Euro 6D',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'Ibrido full della casa che l’ha inventato: in città viaggia in elettrico più della metà del tempo, ' +
      'senza mai doverlo collegare alla presa. Tagliandi Toyota regolari, che estendono la garanzia sulla ' +
      'parte ibrida fino a dieci anni.',
    dotazioni: [
      'Ibrido full self-charging',
      'Sedili in pelle riscaldati',
      'Portellone elettrico',
      'Head-up display',
      'Telecamere 360°',
      'Cerchi in lega da 18"',
      'Navigatore connesso',
      'Cruise control adattivo',
      'Tetto bicolore',
    ],
    immagini: immagini('toyota-yaris-cross-hybrid-lounge'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-16T09:00:00.000Z',
  },
  {
    id: 'vei-mini-cabrio',
    slug: 'mini-cooper-s-cabrio',
    tipo: 'auto',
    marca: 'MINI',
    modello: 'Cooper S',
    allestimento: 'Cabrio Hype',
    anno: 2022,
    chilometri: 34_600,
    prezzo: 28_900,
    prezzoPrecedente: 30_900,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'automatico',
    tipologia: 'cabrio',
    potenzaCv: 178,
    potenzaKw: 131,
    cilindrata: 1998,
    posti: 4,
    porte: 2,
    colore: 'Blu Island metallizzato',
    consumoMisto: 6.6,
    emissioniCo2: 151,
    classeEmissioni: 'Euro 6D',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'Cabrio a capote in tela apribile in diciotto secondi anche in movimento. Vettura di provenienza ' +
      'italiana, sempre garage, con capote controllata e ingrassata in officina prima della messa in ' +
      'vendita. Fatta apposta per le strade costiere d’estate.',
    dotazioni: [
      'Capote elettrica in tela',
      'Roll-bar automatico',
      'Sedili sportivi in pelle',
      'Navigatore con schermo da 8,8"',
      'Fari LED con anello luminoso',
      'Cerchi in lega da 17"',
      'Climatizzatore automatico',
      'Sensori di parcheggio',
      'Scarico sportivo',
    ],
    immagini: immagini('mini-cooper-s-cabrio'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 89,
      settimanale: 520,
      mensile: 1590,
      cauzione: 800,
      kmInclusiGiorno: 200,
      etaMinima: 25,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-06T09:00:00.000Z',
  },
  {
    id: 'vei-fiat-panda',
    slug: 'fiat-panda-1-0-hybrid',
    tipo: 'auto',
    marca: 'Fiat',
    modello: 'Panda',
    allestimento: '1.0 Hybrid Pandina',
    anno: 2025,
    chilometri: 1_900,
    prezzo: 14_900,
    prezzoPrecedente: null,
    condizione: 'km-0',
    alimentazione: 'ibrida',
    cambio: 'manuale',
    tipologia: 'city-car',
    potenzaCv: 70,
    potenzaKw: 51,
    cilindrata: 999,
    posti: 5,
    porte: 5,
    colore: 'Grigio Moda',
    consumoMisto: 5.7,
    emissioniCo2: 129,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'La vettura più pratica che ci sia per muoversi ogni giorno: corta, alta, con una visibilità che ' +
      'nessun SUV riesce a offrire. È anche la base della nostra flotta a noleggio, quindi la conosciamo ' +
      'in ogni dettaglio.',
    dotazioni: [
      'Ibrido a 12 volt',
      'Schermo da 7" con radio DAB',
      'Climatizzatore manuale',
      'Sensori di parcheggio posteriori',
      'Cerchi da 15"',
      'Cruise control',
      'Sei airbag',
    ],
    immagini: immagini('fiat-panda-1-0-hybrid'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 35,
      settimanale: 199,
      mensile: 620,
      cauzione: 300,
      kmInclusiGiorno: 150,
      etaMinima: 21,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-18T09:00:00.000Z',
  },
  {
    id: 'vei-vw-t-roc',
    slug: 'volkswagen-t-roc-2-0-tdi-style',
    tipo: 'auto',
    marca: 'Volkswagen',
    modello: 'T-Roc',
    allestimento: '2.0 TDI 150 CV Style DSG',
    anno: 2024,
    chilometri: 18_700,
    prezzo: 33_500,
    prezzoPrecedente: null,
    condizione: 'aziendale',
    alimentazione: 'diesel',
    cambio: 'automatico',
    tipologia: 'suv',
    potenzaCv: 150,
    potenzaKw: 110,
    cilindrata: 1968,
    posti: 5,
    porte: 5,
    colore: 'Nero Intenso',
    consumoMisto: 5.3,
    emissioniCo2: 139,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'Crossover diesel automatico con pochi chilometri, proveniente da flotta aziendale con manutenzione ' +
      'documentata. Il compromesso migliore per chi fa molta autostrada e vuole comunque una posizione di ' +
      'guida rialzata.',
    dotazioni: [
      'Cambio DSG a 7 rapporti',
      'Digital Cockpit',
      'Navigatore Discover Media',
      'Fari LED Matrix',
      'Cruise control adattivo',
      'Sensori di parcheggio con telecamera',
      'Cerchi in lega da 18"',
      'Climatizzatore bizona',
      'Barre al tetto',
    ],
    immagini: immagini('volkswagen-t-roc-2-0-tdi-style'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 75,
      settimanale: 430,
      mensile: 1340,
      cauzione: 600,
      kmInclusiGiorno: 200,
      etaMinima: 23,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-20T09:00:00.000Z',
  },
  {
    id: 'vei-renault-clio',
    slug: 'renault-clio-tce-90-evolution',
    tipo: 'auto',
    marca: 'Renault',
    modello: 'Clio',
    allestimento: 'TCe 90 Evolution',
    anno: 2026,
    chilometri: 0,
    prezzo: 19_750,
    prezzoPrecedente: 21_300,
    condizione: 'nuovo',
    alimentazione: 'benzina',
    cambio: 'manuale',
    tipologia: 'city-car',
    potenzaCv: 90,
    potenzaKw: 66,
    cilindrata: 999,
    posti: 5,
    porte: 5,
    colore: 'Rosso Fiamma',
    consumoMisto: 5.4,
    emissioniCo2: 123,
    classeEmissioni: 'Euro 6E',
    autonomiaKm: null,
    garanziaMesi: 36,
    descrizione:
      'Utilitaria nuova di fabbrica con tre anni di garanzia della casa. Motore turbo tre cilindri ' +
      'brillante in città e sufficientemente riposante in viaggio, con consumi reali intorno ai sei litri.',
    dotazioni: [
      'Schermo EasyLink da 7"',
      'Apple CarPlay e Android Auto wireless',
      'Climatizzatore automatico',
      'Fari full LED',
      'Retrocamera',
      'Cruise control',
      'Frenata automatica d’emergenza',
      'Cerchi da 16"',
    ],
    immagini: immagini('renault-clio-tce-90-evolution'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-02-22T09:00:00.000Z',
  },

  /* ── Moto ──────────────────────────────────────────────────────────────── */
  {
    id: 'vei-ducati-monster',
    slug: 'ducati-monster-937',
    tipo: 'moto',
    marca: 'Ducati',
    modello: 'Monster',
    allestimento: '937 Plus',
    anno: 2022,
    chilometri: 9_800,
    prezzo: 11_900,
    prezzoPrecedente: 12_900,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'sequenziale',
    tipologia: 'naked',
    potenzaCv: 111,
    potenzaKw: 82,
    cilindrata: 937,
    posti: 2,
    porte: 0,
    colore: 'Rosso Ducati',
    consumoMisto: 5.2,
    emissioniCo2: 121,
    classeEmissioni: 'Euro 5',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Naked bicilindrica di 937 cc con telaio Front Frame in alluminio: 188 chilogrammi in ordine di ' +
      'marcia, quasi venti meno della generazione precedente. Moto di primo proprietario, tagliandata in ' +
      'concessionaria, con cupolino e portatarga corto già montati.',
    dotazioni: [
      'Tre riding mode',
      'Controllo di trazione a otto livelli',
      'Quickshifter up & down',
      'Cruscotto TFT a colori',
      'Cupolino Plus',
      'Frizione antisaltellamento',
      'ABS cornering',
      'Launch control',
    ],
    immagini: immagini('ducati-monster-937'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-22T09:00:00.000Z',
  },
  {
    id: 'vei-bmw-r1300gs',
    slug: 'bmw-r-1300-gs-trophy',
    tipo: 'moto',
    marca: 'BMW',
    modello: 'R 1300 GS',
    allestimento: 'Trophy',
    anno: 2026,
    chilometri: 0,
    prezzo: 22_400,
    prezzoPrecedente: null,
    condizione: 'nuovo',
    alimentazione: 'benzina',
    cambio: 'sequenziale',
    tipologia: 'enduro',
    potenzaCv: 145,
    potenzaKw: 107,
    cilindrata: 1300,
    posti: 2,
    porte: 0,
    colore: 'Racing Blue metallizzato',
    consumoMisto: 4.8,
    emissioniCo2: 112,
    classeEmissioni: 'Euro 5+',
    autonomiaKm: null,
    garanziaMesi: 36,
    descrizione:
      'La maxi enduro di riferimento, nuova e pronta consegna nell’allestimento Trophy con sospensioni ' +
      'semiattive a controllo elettronico e assetto rialzato. Adatta tanto al viaggio in coppia quanto ' +
      'agli sterrati dell’entroterra ogliastrino.',
    dotazioni: [
      'Sospensioni Dynamic ESA',
      'Quattro riding mode Pro',
      'Cruise control adattivo',
      'Cruscotto TFT da 6,5"',
      'Manopole riscaldate',
      'Fari LED adattivi',
      'Paramotore e paramani',
      'Presa USB e presa da 12 V',
      'Keyless Ride',
    ],
    immagini: immagini('bmw-r-1300-gs-trophy'),
    video: null,
    stato: 'disponibile',
    inVetrina: true,
    visibile: true,
    noleggio: {
      giornaliera: 119,
      settimanale: 690,
      mensile: 2100,
      cauzione: 1500,
      kmInclusiGiorno: 250,
      etaMinima: 25,
      consegnaDomicilio: false,
    },
    creatoIl: '2026-02-24T09:00:00.000Z',
  },
  {
    id: 'vei-yamaha-mt07',
    slug: 'yamaha-mt-07',
    tipo: 'moto',
    marca: 'Yamaha',
    modello: 'MT-07',
    allestimento: 'ABS',
    anno: 2023,
    chilometri: 6_200,
    prezzo: 7_900,
    prezzoPrecedente: null,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'sequenziale',
    tipologia: 'naked',
    potenzaCv: 73,
    potenzaKw: 54,
    cilindrata: 689,
    posti: 2,
    porte: 0,
    colore: 'Icon Blue',
    consumoMisto: 4.3,
    emissioniCo2: 100,
    classeEmissioni: 'Euro 5',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Bicilindrica CP2 depotenziabile a 35 kW per le patenti A2: si compra da neopatentati e si tiene ' +
      'anche dopo. Pochi chilometri, mai caduta, gomme al 70%.',
    dotazioni: [
      'ABS a due canali',
      'Strumentazione LCD invertita',
      'Fari LED',
      'Depotenziabile A2',
      'Sella comfort',
      'Forcella regolabile nel precarico',
    ],
    immagini: immagini('yamaha-mt-07'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 69,
      settimanale: 390,
      mensile: 1190,
      cauzione: 800,
      kmInclusiGiorno: 200,
      etaMinima: 21,
      consegnaDomicilio: false,
    },
    creatoIl: '2026-01-30T09:00:00.000Z',
  },
  {
    id: 'vei-honda-africa-twin',
    slug: 'honda-africa-twin-crf1100l',
    tipo: 'moto',
    marca: 'Honda',
    modello: 'Africa Twin',
    allestimento: 'CRF1100L Adventure Sports DCT',
    anno: 2021,
    chilometri: 18_400,
    prezzo: 13_500,
    prezzoPrecedente: 14_800,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'automatico',
    tipologia: 'enduro',
    potenzaCv: 102,
    potenzaKw: 75,
    cilindrata: 1084,
    posti: 2,
    porte: 0,
    colore: 'Tricolore HRC',
    consumoMisto: 4.9,
    emissioniCo2: 114,
    classeEmissioni: 'Euro 5',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Maxi enduro con cambio a doppia frizione DCT: si guida senza leva frizione, una comodità che nel ' +
      'traffico e sugli sterrati cambia la giornata. Serbatoio da 24,8 litri, oltre cinquecento chilometri ' +
      'di autonomia reale.',
    dotazioni: [
      'Cambio automatico DCT',
      'Sospensioni Showa EERA',
      'Cruise control',
      'Cruscotto touch da 6,5"',
      'Manopole riscaldate',
      'Paramotore tubolare',
      'Faro LED',
      'Controllo di trazione a sette livelli',
    ],
    immagini: immagini('honda-africa-twin-crf1100l'),
    video: null,
    stato: 'prenotato',
    inVetrina: false,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-08T09:00:00.000Z',
  },
  {
    id: 'vei-vespa-gts',
    slug: 'vespa-gts-300-super',
    tipo: 'moto',
    marca: 'Vespa',
    modello: 'GTS',
    allestimento: '300 Super Tech',
    anno: 2026,
    chilometri: 0,
    prezzo: 7_290,
    prezzoPrecedente: null,
    condizione: 'nuovo',
    alimentazione: 'benzina',
    cambio: 'automatico',
    tipologia: 'scooter',
    potenzaCv: 24,
    potenzaKw: 17.5,
    cilindrata: 278,
    posti: 2,
    porte: 0,
    colore: 'Blu Energia lucido',
    consumoMisto: 3.4,
    emissioniCo2: 79,
    classeEmissioni: 'Euro 5+',
    autonomiaKm: null,
    garanziaMesi: 24,
    descrizione:
      'La Vespa più potente di sempre, nuova e disponibile in pronta consegna. Scocca portante in acciaio, ' +
      'ruote da dodici pollici e sella a due posti: il mezzo giusto per muoversi d’estate lungo la costa ' +
      'senza pensieri di parcheggio.',
    dotazioni: [
      'Cruscotto TFT a colori',
      'Connettività Vespa MIA',
      'ABS a due canali',
      'Controllo di trazione ASR',
      'Fari full LED',
      'Presa USB nel vano portaoggetti',
      'Cavalletto centrale ed elettrico',
    ],
    immagini: immagini('vespa-gts-300-super'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 45,
      settimanale: 250,
      mensile: 760,
      cauzione: 400,
      kmInclusiGiorno: 150,
      etaMinima: 18,
      consegnaDomicilio: true,
    },
    creatoIl: '2026-02-26T09:00:00.000Z',
  },
  {
    id: 'vei-kawasaki-ninja',
    slug: 'kawasaki-ninja-zx-6r',
    tipo: 'moto',
    marca: 'Kawasaki',
    modello: 'Ninja',
    allestimento: 'ZX-6R 636',
    anno: 2020,
    chilometri: 14_300,
    prezzo: 9_900,
    prezzoPrecedente: null,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'sequenziale',
    tipologia: 'sportiva',
    potenzaCv: 130,
    potenzaKw: 96,
    cilindrata: 636,
    posti: 2,
    porte: 0,
    colore: 'Verde Lime KRT',
    consumoMisto: 6.1,
    emissioniCo2: 142,
    classeEmissioni: 'Euro 4',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Supersportiva quattro cilindri con cilindrata maggiorata a 636 cc, più elastica della rivale da 600 ' +
      'nell’uso stradale. Sempre in garage, catena e pastiglie nuove, mai vista una pista.',
    dotazioni: [
      'Quickshifter',
      'Controllo di trazione KTRC',
      'Due mappature motore',
      'Forcella Showa SFF-BP',
      'ABS',
      'Scarico Akrapovič omologato',
      'Terminali paratelaio',
    ],
    immagini: immagini('kawasaki-ninja-zx-6r'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: null,
    creatoIl: '2026-01-25T09:00:00.000Z',
  },
  {
    id: 'vei-harley-nightster',
    slug: 'harley-davidson-nightster',
    tipo: 'moto',
    marca: 'Harley-Davidson',
    modello: 'Nightster',
    allestimento: 'RH975',
    anno: 2023,
    chilometri: 7_600,
    prezzo: 13_900,
    prezzoPrecedente: 15_200,
    condizione: 'usato',
    alimentazione: 'benzina',
    cambio: 'sequenziale',
    tipologia: 'custom',
    potenzaCv: 90,
    potenzaKw: 66,
    cilindrata: 975,
    posti: 2,
    porte: 0,
    colore: 'Vivid Black',
    consumoMisto: 4.8,
    emissioniCo2: 112,
    classeEmissioni: 'Euro 5',
    autonomiaKm: null,
    garanziaMesi: 12,
    descrizione:
      'Custom moderna con il bicilindrico Revolution Max raffreddato a liquido: la posizione di guida ' +
      'rilassata di sempre, con freni e ciclistica di questo secolo. Sella bassa a 705 millimetri, adatta ' +
      'anche a chi non è altissimo.',
    dotazioni: [
      'Tre riding mode',
      'ABS cornering',
      'Controllo di trazione',
      'Strumentazione circolare digitale',
      'Sospensioni posteriori regolabili',
      'Scarico ribassato',
      'Sella comfort a due posti',
    ],
    immagini: immagini('harley-davidson-nightster'),
    video: null,
    stato: 'disponibile',
    inVetrina: false,
    visibile: true,
    noleggio: {
      giornaliera: 99,
      settimanale: 570,
      mensile: 1750,
      cauzione: 1200,
      kmInclusiGiorno: 200,
      etaMinima: 25,
      consegnaDomicilio: false,
    },
    creatoIl: '2026-02-04T09:00:00.000Z',
  },
]
