import type { Piatto } from '@/lib/tipi'

/**
 * Menù di partenza.
 *
 * Al primo avvio questi piatti vengono copiati nell'archivio (`src/lib/archivio.ts`);
 * da quel momento la fonte di verità è l'archivio, modificabile dal pannello di
 * amministrazione. Questo file resta il contenuto di riferimento per un ripristino.
 */
export const MENU_INIZIALE: Piatto[] = [
  // ─── Antipasti ────────────────────────────────────────────────────────────
  {
    id: 'ant-vitello-tonnato',
    nome: 'Vitello tonnato',
    descrizione:
      'Girello di fassona cotto a bassa temperatura, salsa tonnata montata a mano, capperi di Pantelleria.',
    prezzo: 16,
    categoria: 'antipasti',
    allergeni: ['pesce', 'uova'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/ant-vitello-tonnato.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'ant-burrata-pomodorini',
    nome: 'Burrata e pomodorini confit',
    descrizione:
      'Burrata pugliese, pomodorini datterini canditi al timo, olio extravergine Frantoio, basilico.',
    prezzo: 14,
    categoria: 'antipasti',
    allergeni: ['latte'],
    etichetta: null,
    immagine: '/immagini/piatti/ant-burrata-pomodorini.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'ant-tartare-chianina',
    nome: 'Tartare di Chianina',
    descrizione:
      'Battuta al coltello, tuorlo marinato, senape antica, cialda di pane toscano e polvere di capperi.',
    prezzo: 19,
    categoria: 'antipasti',
    allergeni: ['uova', 'glutine', 'senape'],
    etichetta: 'novita',
    immagine: '/immagini/piatti/ant-tartare-chianina.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 3,
  },
  {
    id: 'ant-carciofi-fritti',
    nome: 'Carciofi fritti e pecorino',
    descrizione:
      'Carciofi violetti in tempura leggera, fonduta di pecorino di fossa, pepe nero di Sarawak.',
    prezzo: 13,
    categoria: 'antipasti',
    allergeni: ['glutine', 'latte'],
    etichetta: null,
    immagine: '/immagini/piatti/ant-carciofi-fritti.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 4,
  },
  {
    id: 'ant-crudo-gambero',
    nome: 'Crudo di gambero rosso',
    descrizione:
      'Gambero rosso di Mazara, olio al limone, finocchietto selvatico e pistacchio di Bronte.',
    prezzo: 22,
    categoria: 'antipasti',
    allergeni: ['crostacei', 'frutta a guscio'],
    etichetta: null,
    immagine: '/immagini/piatti/ant-crudo-gambero.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 5,
  },

  // ─── Primi ────────────────────────────────────────────────────────────────
  {
    id: 'pri-tagliolini-tartufo',
    nome: 'Tagliolini al tartufo nero',
    descrizione:
      'Tagliolini tirati a mano, burro di malga, parmigiano trentasei mesi, tartufo nero di stagione.',
    prezzo: 24,
    categoria: 'primi',
    allergeni: ['glutine', 'uova', 'latte'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/pri-tagliolini-tartufo.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'pri-risotto-zafferano',
    nome: 'Risotto allo zafferano e midollo',
    descrizione:
      'Carnaroli riserva, zafferano in pistilli, midollo scottato alla brace, riduzione di vino rosso.',
    prezzo: 21,
    categoria: 'primi',
    allergeni: ['latte', 'solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/pri-risotto-zafferano.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 2,
  },
  {
    id: 'pri-pappardelle-cinghiale',
    nome: 'Pappardelle al cinghiale',
    descrizione:
      'Ragù di cinghiale brasato quattro ore nel Chianti, bacche di ginepro, pappardelle all’uovo.',
    prezzo: 19,
    categoria: 'primi',
    allergeni: ['glutine', 'uova', 'sedano', 'solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/pri-pappardelle-cinghiale.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },
  {
    id: 'pri-ravioli-ricotta',
    nome: 'Ravioli ricotta e limone',
    descrizione:
      'Ravioli di ricotta di pecora, scorza di limone di Amalfi, burro nocciola e mandorle tostate.',
    prezzo: 18,
    categoria: 'primi',
    allergeni: ['glutine', 'uova', 'latte', 'frutta a guscio'],
    etichetta: null,
    immagine: '/immagini/piatti/pri-ravioli-ricotta.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 4,
  },
  {
    id: 'pri-spaghetti-vongole',
    nome: 'Spaghetti alle vongole veraci',
    descrizione:
      'Spaghetti di grano Senatore Cappelli, vongole veraci, aglio in camicia, prezzemolo e bottarga.',
    prezzo: 20,
    categoria: 'primi',
    allergeni: ['glutine', 'molluschi', 'pesce'],
    etichetta: null,
    immagine: '/immagini/piatti/pri-spaghetti-vongole.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 5,
  },

  // ─── Secondi ──────────────────────────────────────────────────────────────
  {
    id: 'sec-guancia-brasata',
    nome: 'Guancia di vitello brasata',
    descrizione:
      'Guancia brasata nel Sangiovese, purè di patate alla vaniglia, cipollotto glassato.',
    prezzo: 26,
    categoria: 'secondi',
    allergeni: ['latte', 'sedano', 'solfiti'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/sec-guancia-brasata.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'sec-baccala-mantecato',
    nome: 'Baccalà mantecato e cicoria',
    descrizione:
      'Baccalà islandese mantecato, cicoria ripassata, crema di ceci e olio al rosmarino.',
    prezzo: 24,
    categoria: 'secondi',
    allergeni: ['pesce'],
    etichetta: null,
    immagine: '/immagini/piatti/sec-baccala-mantecato.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'sec-melanzana-parmigiana',
    nome: 'Parmigiana di melanzane',
    descrizione:
      'Melanzane violette, pomodoro San Marzano, basilico e parmigiano. Piatto vegetariano.',
    prezzo: 18,
    categoria: 'secondi',
    allergeni: ['latte'],
    etichetta: null,
    immagine: '/immagini/piatti/sec-melanzana-parmigiana.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },
  {
    id: 'sec-agnello-erbe',
    nome: 'Carré d’agnello alle erbe',
    descrizione:
      'Carré in crosta di erbe di campo, topinambur arrosto, jus all’aglio nero.',
    prezzo: 29,
    categoria: 'secondi',
    allergeni: ['glutine', 'senape'],
    etichetta: 'novita',
    immagine: '/immagini/piatti/sec-agnello-erbe.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 4,
  },

  // ─── Pizza ────────────────────────────────────────────────────────────────
  {
    id: 'piz-margherita-dop',
    nome: 'Margherita DOP',
    descrizione:
      'Impasto a lievitazione naturale 48 ore, San Marzano DOP, fiordilatte di Agerola, basilico.',
    prezzo: 11,
    categoria: 'pizza',
    allergeni: ['glutine', 'latte'],
    etichetta: null,
    immagine: '/immagini/piatti/piz-margherita-dop.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'piz-tartufo-funghi',
    nome: 'Tartufo e funghi',
    descrizione:
      'Fiordilatte, funghi porcini trifolati, crema al tartufo nero, prezzemolo e olio evo.',
    prezzo: 16,
    categoria: 'pizza',
    allergeni: ['glutine', 'latte'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/piz-tartufo-funghi.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'piz-bufala-crudo',
    nome: 'Bufala e crudo di Parma',
    descrizione:
      'Base bianca, bufala campana DOP, crudo di Parma 24 mesi, rucola selvatica e scaglie di grana.',
    prezzo: 15,
    categoria: 'pizza',
    allergeni: ['glutine', 'latte'],
    etichetta: null,
    immagine: '/immagini/piatti/piz-bufala-crudo.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },
  {
    id: 'piz-ortolana',
    nome: 'Ortolana di stagione',
    descrizione:
      'Verdure dell’orto grigliate, pomodoro, fiordilatte, pesto di basilico. Piatto vegetariano.',
    prezzo: 13,
    categoria: 'pizza',
    allergeni: ['glutine', 'latte', 'frutta a guscio'],
    etichetta: null,
    immagine: '/immagini/piatti/piz-ortolana.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 4,
  },

  // ─── Carne ────────────────────────────────────────────────────────────────
  {
    id: 'car-fiorentina',
    nome: 'Bistecca alla fiorentina',
    descrizione:
      'Chianina IGP frollata 40 giorni, cotta sulla brace di leccio. Prezzo all’etto, minimo 1 kg.',
    prezzo: 9,
    categoria: 'carne',
    allergeni: [],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/car-fiorentina.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'car-tagliata-rucola',
    nome: 'Tagliata di manzo',
    descrizione:
      'Controfiletto scottato alla brace, rucola, pomodorini e scaglie di parmigiano.',
    prezzo: 27,
    categoria: 'carne',
    allergeni: ['latte'],
    etichetta: null,
    immagine: '/immagini/piatti/car-tagliata-rucola.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'car-costine-glassate',
    nome: 'Costine di maiale glassate',
    descrizione:
      'Costine cotte 12 ore a bassa temperatura, glassa al miele di castagno e senape.',
    prezzo: 23,
    categoria: 'carne',
    allergeni: ['senape'],
    etichetta: null,
    immagine: '/immagini/piatti/car-costine-glassate.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },

  // ─── Pesce ────────────────────────────────────────────────────────────────
  {
    id: 'pes-branzino-forno',
    nome: 'Branzino in crosta di sale',
    descrizione:
      'Branzino selvaggio cotto in crosta di sale marino, olio al limone e verdure di stagione.',
    prezzo: 28,
    categoria: 'pesce',
    allergeni: ['pesce'],
    etichetta: null,
    immagine: '/immagini/piatti/pes-branzino-forno.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'pes-polpo-brace',
    nome: 'Polpo alla brace',
    descrizione:
      'Tentacolo scottato sulla brace, crema di patate affumicata, polvere di olive taggiasche.',
    prezzo: 25,
    categoria: 'pesce',
    allergeni: ['molluschi'],
    etichetta: 'novita',
    immagine: '/immagini/piatti/pes-polpo-brace.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'pes-fritto-misto',
    nome: 'Fritto misto dell’Adriatico',
    descrizione:
      'Calamari, gamberi e triglie in frittura leggera, maionese al lime e limone bruciato.',
    prezzo: 24,
    categoria: 'pesce',
    allergeni: ['pesce', 'crostacei', 'molluschi', 'glutine', 'uova'],
    etichetta: null,
    immagine: '/immagini/piatti/pes-fritto-misto.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },

  // ─── Dolci ────────────────────────────────────────────────────────────────
  {
    id: 'dol-tiramisu',
    nome: 'Tiramisù al mascarpone',
    descrizione:
      'Savoiardi fatti in casa, crema al mascarpone, caffè espresso e cacao amaro.',
    prezzo: 9,
    categoria: 'dolci',
    allergeni: ['glutine', 'uova', 'latte'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/dol-tiramisu.jpg',
    visibile: true,
    inEvidenza: true,
    ordine: 1,
  },
  {
    id: 'dol-cioccolato-fondente',
    nome: 'Cuore di cioccolato fondente',
    descrizione:
      'Tortino dal cuore morbido, cioccolato 70%, gelato alla vaniglia del Madagascar.',
    prezzo: 10,
    categoria: 'dolci',
    allergeni: ['glutine', 'uova', 'latte', 'soia'],
    etichetta: null,
    immagine: '/immagini/piatti/dol-cioccolato-fondente.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'dol-cantucci-vinsanto',
    nome: 'Cantucci e Vin Santo',
    descrizione:
      'Cantucci alle mandorle di Prato serviti con Vin Santo del Chianti Classico.',
    prezzo: 8,
    categoria: 'dolci',
    allergeni: ['glutine', 'uova', 'frutta a guscio', 'solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/dol-cantucci-vinsanto.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },

  // ─── Bevande ──────────────────────────────────────────────────────────────
  {
    id: 'bev-acqua',
    nome: 'Acqua minerale 0,75 l',
    descrizione: 'Naturale o frizzante, servita in bottiglia di vetro.',
    prezzo: 3,
    categoria: 'bevande',
    allergeni: [],
    etichetta: null,
    immagine: '/immagini/piatti/bev-acqua.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 1,
  },
  {
    id: 'bev-caffe',
    nome: 'Caffè espresso',
    descrizione: 'Miscela arabica in purezza tostata artigianalmente a Firenze.',
    prezzo: 2,
    categoria: 'bevande',
    allergeni: [],
    etichetta: null,
    immagine: '/immagini/piatti/bev-caffe.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'bev-cocktail-aurea',
    nome: 'Signature “Aurea”',
    descrizione:
      'Gin toscano, vermouth bianco, infuso di camomilla e scorza d’arancia bruciata.',
    prezzo: 12,
    categoria: 'bevande',
    allergeni: ['solfiti'],
    etichetta: 'novita',
    immagine: '/immagini/piatti/bev-cocktail-aurea.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },

  // ─── Vini ─────────────────────────────────────────────────────────────────
  {
    id: 'vin-chianti-classico',
    nome: 'Chianti Classico DOCG',
    descrizione:
      'Sangiovese in purezza, 14 mesi in botte grande. Ciliegia, viola e tabacco dolce.',
    prezzo: 32,
    categoria: 'vini',
    allergeni: ['solfiti'],
    etichetta: 'consigliato',
    immagine: '/immagini/piatti/vin-chianti-classico.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 1,
  },
  {
    id: 'vin-vermentino',
    nome: 'Vermentino di Bolgheri',
    descrizione:
      'Bianco fresco e sapido, note di agrumi e macchia mediterranea. Ottimo con il pesce.',
    prezzo: 28,
    categoria: 'vini',
    allergeni: ['solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/vin-vermentino.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 2,
  },
  {
    id: 'vin-brunello',
    nome: 'Brunello di Montalcino DOCG',
    descrizione:
      'Annata di riferimento, cinque anni di affinamento. Struttura ampia e tannino elegante.',
    prezzo: 78,
    categoria: 'vini',
    allergeni: ['solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/vin-brunello.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 3,
  },
  {
    id: 'vin-franciacorta',
    nome: 'Franciacorta Brut DOCG',
    descrizione:
      'Bollicina metodo classico, 30 mesi sui lieviti. Crosta di pane e agrumi canditi.',
    prezzo: 42,
    categoria: 'vini',
    allergeni: ['solfiti'],
    etichetta: null,
    immagine: '/immagini/piatti/vin-franciacorta.jpg',
    visibile: true,
    inEvidenza: false,
    ordine: 4,
  },
]
